baseURL = 'https://samir1498.github.io/blog-comparisons-qna/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hugo-bearblog"
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "Comparisons"
    url = "/comparisons/"
    weight = 3

  [[menu.main]]
    name = "Q&A"
    url = "/questions/"
    weight = 4

